### ISSUE TITLE
Node.js 10.13.0 도 지원할 수 있도록 요청드립니다.

### ISSUE THREAD

**Issue by sorilove** [koalanlp/nodejs-support#7]
### 기초정보
- Node.js 버전은요? (Version of the Node.js)? **10.13.0**
- KoalaNLP 버전은요? (Version of KoalaNLP)? **1.3.4**
- 문제의 유형은 어떤 것인가요? (Type of this issue)?
  - [ ] 버그리포트. Bug report
  - [ ] 개선점제안. Idea/Suggestion for a improvement
  - [ ] 사용법질문. Question about using KoalaNLP
  - [x] 기타. Other

### 본문
- 아래에 본문을 입력해주세요. (Describe your issue here.)
- Windows 10 에서 Node.js 10.13.0 으로 KoalaNLP 설치가 되지 않습니다. 동일한 환경에서 Node.js 버전을 8.x 로 변경하고 설치하면 정상 처리 및 작동까지 문제 없는 것을 확인했습니다.
- Node.js 10.13.0 도 지원할 수 있도록 요청드립니다.

**Comment by nearbydelta** [comment]
의존하는 일부 패키지가 낡았었습니다. 
패키지 버전을 올려서 리눅스에서는 정상인데 Win 10은 직접 확인해주실 수 있을까요?
1.3.5 버전을 사용해보시면 됩니다.

**Comment by sorilove** [comment]
감사합니다. Windows 10 에서 Node.js 10.13.0 으로 설치 및 정상 작동 확인하였습니다.
